# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('locationName', models.CharField(blank=True, default='', max_length=200)),
                ('xcoordinate', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('ycoordinate', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
