# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('userNumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', models.FloatField(verbose_name='Location')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
